apiVersion: v1
kind: PersistentVolume
metadata:
  name: es
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/es/