apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mariadb/