apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/minio/