apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/postgres/